title: Mitch Stapleton
email: mitch.stapleton@gmail.com
description: description
baseurl: ""# the subpath of your site, e.g. /blog
url: http://mitchstapleton.github.io
twitter_username: mitchstapleton
github_username:  mitchstapleton
port: 3000

sass:
  style: compressed
  
paginate: 12
paginate_path: "/:num/"

author_img_s: /img/author_s.png
author_img: /img/author.png

navigation:
  - text: Home
    url: /
  - text: Categories
    url: /categories.html
  - text: Tags
    url: /tags.html
    
read_more: Read More
env: production
minify_html: false # Set to true only when it is production. Increase significant build time.

# Build settings
markdown: kramdown

sticky: sticky # Tag used for sticky post
sticky_count: 3 # Number of sticky post shown

sass:
    sass_dir: assets/css
    style: nested
    
# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
